messages:  {} # tirar os {} e os # para criar uma config default (para usar cor use §)
  #'3':
  #- ''
  #- '§cPlugin created of by: SigmaNetwork'
  #- ''
system-active: true #true para ativar o plugin, false para desativar o plugin
sound-active: true #mandar o som para todos jogadores onlines, hora que mandar alguma das mensagens.
sound-name: LEVEL_UP #https://www.spigotmc.org/wiki/cc-sounds-list/
system-delay: 60 #em segundos
